= tjur
A new Language


== What's with the name?
Because, it comes from Clojure, it is Typed, and it has four letters!


== Goals

. Strictly typed, inferred, optionally dynamically typed.
. Compiled, with optional jit and interpreter.
. Flexible memory management: (Manual, rust style ownership tracking, reference counted, garbage collected)
. Interoperability with C++
. Target WebAssembly
. Flexible module system. (ES6 and go inspired. Bundler and Homebrew style dependency resolution)
. Node style async API. Agent based multithreading. (Everything is Agent local. CSP style communication)
. Tooling. (a la. GoDoc, style, etc.)


== Notes on Goals

. On the side on being compiled, it must be noted that there are two different important sides to this:
  .. First, whole program optimization is invaluable. For example it might be possible to determine through
    analize that a persistent DS can be converted to a mutable DS and buy a tremendous performance.
  .. Second, what rust noted about importance of independence of modules of code and not requiring a special
    runtime.
. On the goal of memory management, Rich's argument is that that blongs to the era of Place oriented programming (PLOP).
  However, to compete with the performance of C, going that road seems inevitable. There might still exist some remedy.
  People from ObjC land or Java land don't suffer much from the penalty of ARC or GC, but even that slight drawback might
  be eliminable through name analysis. Investigate if it is possible to enumerate all possible names of places in a program
  an insert right kind of memory management automatically.
. About asyncronity and AOP it must be noted that in the end it seems that CSP looks more fundamental than agents and FRP.
  I must deside what is the right abstraction to be putted there as a basic building block. AOP or CSP?

== Ideas

. Fine grained Warning and helpful notification system. Let users decide what they want. But inform them of the consequences.
. Auto infer properties of code. Whatever can not be infered doesn't any value for implementation. Expose sane restrictions so that things could be infered. However, let users override the system.
. Breakdown the system to completely customiseable and replaceable subsystems. Asume that the compiler itself is a highly specialized interpreter.
. As Alan Kay, The inventor of Object-oriented, says that he thaught about OO as cells communicating with each other, only through messages, Agent based concurrency comes real close. You could say that Pony almost got it perfectly. Investigate the well of ideas here. Smalltalk, Agent based messaging, CSP, Node style asyncrony, Promises, My idea about implicit context, etc.
. Being able to compile on module boundaries seems a serious yet justifyable restriction. I need to think about it.
. Facebook's flow type checker does a wonderful job. Might want to get inspired by it! ;)
. For the shape of code and data there is this idea that data is a black box with some shiped primitives to move it. Like presenting natural numbers as a zero, which we do not undrestand it any further, and the SUCC operator. Then other operations can be built on top. This idea sits well, in my opinion, with the computer architecture, and has its relations with pipelining, range based programming, and glorified Stuart Sierra's OOP or transducers.
. Smalltalk like live environment, and a framework to easily create such kind of things is very very helpful. Afterall tooling is also part of environment. Imagin that people created live env for games like unity without a need for build and deploy. Gamers been on the same env that the game devs were!

== Crasy Stupid Programming Language

... is a programmable virtual machine spesification with a predifined set of things set in the stone. And a default program.
The constant bits are a definition of a strongly statically typed minimal abstract syntax tree and a set of intrinsics, like interpretting/jitting/compiling the AST.
The default program is an interpretter which generates AST. However, the interpretter is completely dynamic and is in the spirit of smalltalk. Which means that you can completely replace it with something else, for example a ruby parser or something entirely different, in the middle of the interpretation.
Also, the specification introduces points of vendor extensions, in the spirit of opengl vendor extensions, for functionalities like custom memory managers or other target specific features.
