= tjur
A new Language


== What's with the name?
Because, it comes from Clojure, it is Typed, and it has four letters!


== Goals

. Strictly typed, inferred, optionally dynamically typed.
. Compiled, with optional jit and interpreter.
. Flexible memory management: (Manual, rust style ownership tracking, reference counted, garbage collected)
. Interoperability with C++
. Target WebAssembly
. Flexible module system. (ES6 and go inspired. Bundler and Homebrew style dependency resolution)
. Node style async API. Agent based multithreading. (Everything is Agent local. CSP style communication)


== Ideas

. Fine grained Warning and helpful notification system. Let users decide what they want. But inform them of the consequences.
. Auto infer properties of code. Whatever can not be infered doesn't any value for implementation. Expose sane restrictions so that things could be infered. However, let users override the system.
. Breakdown the system to completely customiseable and replaceable subsystems. Asume that the compiler itself is a highly specialized interpreter.
. As Alan Kay, The inventor of Object-oriented, says that he thaught about OO as cells communicating with each other, only through messages, Agent based concurrency comes real close. You could say that Pony almost got it perfectly. Investigate the well of ideas here. Smalltalk, Agent based messaging, CSP, Node style asyncrony, Promises, My idea about implicit context, etc.
